type Query {
  post(id: ID!): Post

  posts(
    first: Int
    after: String
    last: Int
    before: String
  ): PostsConnection!

  user(id: ID!): User

  users(
    first: Int
    after: String
    last: Int
    before: String
  ): UsersConnection!
}
