type User {
  id: ID!

  firstName: String!

  lastName: String

  email: String!

  isActive: Boolean!

  posts(
    first: Int
    after: String
    last: Int
    before: String
  ): PostsConnection!
}
